version: '3.6'

services:
  torchserve_qa:
    image: torchserve_custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    container_name: torchserve_custom